routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function() {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/profilesettings','App\Http\Controllers\HomeController@profilesettings')->name('profilesettings');
    Route::post('/updateprofile','App\Http\Controllers\HomeController@updateprofilesettings')->name('updateprofile');
    Route::group(['middleware'=>['role:admin']],function(){

    Route::resource('category' , 'App\Http\Controllers\CategoryController');

    Route::get('/cms','App\Http\Controllers\CmsController@index')->name('cms');
    Route::post('/updateaboutus','App\Http\Controllers\CmsController@updateaboutussection')->name('updateaboutus');
    Route::post('/updatetermsandcondition', 'App\Http\Controllers\CmsController@updatetermsandconditionsection')->name('updatetermsandcondition');
    Route::post('/updatewelcomevideo', 'App\Http\Controllers\CmsController@updatewelcomevideosection')->name('updatewelcomevideo');
    Route::get('/adduser', 'App\Http\Controllers\UserController@create')->name('createuser');
    Route::post('/saveuser', 'App\Http\Controllers\UserController@store')->name('saveuser');
    Route::get('/userslist','App\Http\Controllers\UserController@index')->name('userslist');
    Route::get('/userdetail/{id}','App\Http\Controllers\UserController@viewuserdetail')->name('userdetail');
    Route::post('/updateuser', 'App\Http\Controllers\UserController@updateuserdetail')->name('updateuser');
    Route::get('/paymentsettings','App\Http\Controllers\HomeController@paymentsettings')->name('paymentsettings');
    Route::post('/updatepaymentsettings', 'App\Http\Controllers\HomeController@updatepaymentsettingssection')->name('updatepaymentsettings');
    Route::post('/updatecreditpackages','App\Http\Controllers\HomeController@updatecreditpackagessection')->name('updatecreditpackages');
    Route::get('/customerjob/{id}','App\Http\Controllers\UserController@customerjobdetail')->name('customerjob');
    Route::get('/deleteestablishmentimagebyadmin/{id}','App\Http\Controllers\UserController@deleteestablishmentimagebyadmin')->name('deleteestablishmentimagebyadmin');
    Route::get('/supplierjob/{id}','App\Http\Controllers\UserController@supplierjobdetail')->name('supplierjob');




    });
    Route::group(['middleware'=>['role:customer']],function(){
    Route::get('/newservice','App\Http\Controllers\ServiceController@index')->name('newservice');
    Route::post('/savejobrequest','App\Http\Controllers\ServiceController@savecustomerjob')->name('savejobrequest');
    Route::get('/customerinbox','App\Http\Controllers\ServiceController@customerinbox')->name('customerinbox');
    //Route::get('/customerjob','App\Http\Controllers\UserController@customerjobdetail')->name('customerjob');
    Route::get('/specificjobrequests/{id}','App\Http\Controllers\ServiceController@specificjobrequests')->name('specificjobrequests');
    Route::get('/viewsupplierprofile/{id}/{jobid}', 'App\Http\Controllers\ServiceController@specificsupplierforjobdetail')->name('viewsupplierprofile');
    Route::get('/awardjob/{jobid}/{supplierid}', 'App\Http\Controllers\ServiceController@awardjobtosupplier')->name('awardjob');
    Route::get('/jobdetail','App\Http\Controllers\ServiceController@jobdetail')->name('jobdetail');
    Route::post('/givereview','App\Http\Controllers\ServiceController@giveSupplierReview')->name('givereview');


    });
    Route::group(['middleware'=>['role:supplier']],function(){
        Route::get('/myjobdetail/{id}','App\Http\Controllers\ServiceController@myjobdetail')->name('myjobdetail');
        Route::get('/acceptjobDetail/{id}','App\Http\Controllers\ServiceController@acceptthisjob')->name('acceptjobDetail');
        Route::get('/reviewPendingjobDetail/{id}','App\Http\Controllers\ServiceController@permissiontoreviewthisjob')->name('reviewPendingjobDetail');
        Route::get('/buycredits','App\Http\Controllers\ServiceController@buycredits')->name('buycredits');
        Route::get('/addcredits/{id}', 'App\Http\Controllers\ServiceController@addcredits')->name('addcredits');
        Route::get('/jobdetail','App\Http\Controllers\UserController@detailforsupplier')->name('jobdetail');
        Route::get('/supplierestablishments','App\Http\Controllers\ServiceController@supplierestablishments')->name('supplierestablishments');
        Route::post('/addsupplierestablishment', 'App\Http\Controllers\ServiceController@savesupplierestablishment')->name('addsupplierestablishment');
        Route::get('/establishmentimages','App\Http\Controllers\ServiceController@establishmentimages')->name('establishmentimages');
        Route::post('/saveestablishmentimages', 'App\Http\Controllers\ServiceController@saveestablishmentimages')->name('establshmentimages.store');
        Route::post('/updatesupplierdetail','App\Http\Controllers\ServiceController@updatesupplierestablishment')->name('updatesupplierestablishment');
        Route::get('/supplierinbox','App\Http\Controllers\ServiceController@supplierinbox')->name('supplierinbox');
        Route::get('/deleteestablishmentimage/{id}','App\Http\Controllers\ServiceController@deleteestablishmentimage')->name('deleteestablishmentimage');

    });
    /* Route::get('/customerjob','App\Http\Controllers\UserController@customerjobdetail')->name('customerjob');
    Route::get('/jobdetail','App\Http\Controllers\UserController@detailforsupplier')->name('jobdetail');
    Route::get('/cms','App\Http\Controllers\CmsController@index')->name('cms');
    Route::get('/newservice','App\Http\Controllers\ServiceController@index')->name('newservice');
    Route::get('/customerinbox','App\Http\Controllers\ServiceController@customerinbox')->name('customerinbox');
    Route::get('/specificjobrequests','App\Http\Controllers\ServiceController@specificjobrequests')->name('specificjobrequests');
    Route::get('/jobdetail','App\Http\Controllers\ServiceController@jobdetail')->name('jobdetail');
    Route::get('/supplierinbox','App\Http\Controllers\ServiceController@supplierinbox')->name('supplierinbox');
    Route::get('/myjobdetail','App\Http\Controllers\ServiceController@myjobdetail')->name('myjobdetail');
    Route::get('/paymentsettings','App\Http\Controllers\HomeController@paymentsettings')->name('paymentsettings');
    Route::get('/profilesettings','App\Http\Controllers\HomeController@profilesettings')->name('profilesettings');
    Route::get('/buycredits','App\Http\Controllers\ServiceController@buycredits')->name('buycredits');
    Route::get('/supplierestablishments','App\Http\Controllers\ServiceController@supplierestablishments')->name('supplierestablishments');
    Route::get('/establishmentimages','App\Http\Controllers\ServiceController@establishmentimages')->name('establishmentimages'); */
    });

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $guarded = [];
    public function categories()
    {
        return $this->hasMany(Category::class);
    }
    public function parentCategory()
    {
        return $this->belongsTo(Category::class,'category_id');
    }
    public function childrenCategories()
    {
        return $this->hasMany(Category::class)->with('categories');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Requests\CategorySaveRequest;
use App\Http\Requests\CategoryUpdateRequest;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $category = Category::all();
        return view('category.list',compact('category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = Category::select('*')
                            ->where('status', true)
                            ->get();
        return view('category.add',compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategorySaveRequest $request)
    {
       try{
           DB::beginTransaction();
           if($request->hasFile('categoryimage'))
           {
               $path = $request->file('categoryimage')->store('public/category');
           }
           if($path)
           {
               $data = [
                   'name' =>$request->name,
                   'category_id' => ($request->category_id==0) ? NULL : $request->category_id ,
                   'categoryimage' => $path,
                   'status' => $request->status
               ];
               Category::create($data);
               DB::commit();
               Toastr::success('Category Added Successfully','Success');
               return redirect('/category');
           }
       }
       catch (\Exception $e)
       {
           $res=$e->getMessage();

           DB::rollback();
           Toastr::error('Something went wrong. Please try again','Danger');
           return redirect('/category');
       }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::select('*')
            ->where('status', true)
            ->get();
       $categories = Category::find($id);

       return view ('category.edit',compact('categories', 'category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryUpdateRequest $request, $id)
    {
        $category = Category::find($id);
        $category->name = $request->name;
        $category->category_id = ($request->category_id==0) ? NULL : $request->category_id;
        $category->status = $request->status;
        if ($request->hasFile('categoryimage')) {
            $path = $request->file('categoryimage')->store('public/category');
            $category->categoryimage = $path;
        }
        else{
            $category->categoryimage = $request->oldimage;
        }
        $category->save();
        Toastr::success('Category Updated Successfully','Success');
        return redirect('/category');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::where('category_id', '=', $id)->exists();
        if($category)
        {
            Toastr::error('Parent Category. Cannot be deleted','Alert');
            return redirect('/category');
        }
        else{
            $category = Category::find($id);
            Storage::delete($category->categoryimage); //delete image from storage
            $category->delete();
            Toastr::error('Category deleted Successfully','Alert');
            return redirect('/category');
        }


    }
}

resources/views/category/add.blade.php
@extends('layouts.sidebar')
@section('content1')
    <div class="col-md-9">
        <form action="{{ route('category.store') }}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="InputCategoryName">Category Name</label>
                <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" id="InputCategoryName" placeholder="Enter Category Name">
                @error('name')
                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                @enderror
            </div>
            <div class="form-group">
                <label for="selectParentCategory">Parent Category</label>
                <select class="form-control" id="selectParentCategory" name="category_id">
                    <option value="0">No Parent</option>
                    @foreach($category as $row)
                    <option value="{{ $row->id }}">{{ $row->name }}</option>
                    @endforeach
                   </select>
            </div>
            <div class="form-group">
                <label for="InputCategoryImage">Category Image</label>
                <input type="file" name="categoryimage" class="form-control @error('categoryimage') is-invalid @enderror" id="InputCategoryImage">
                @error('categoryimage')
                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                @enderror
            </div>
            <div class="form-group">
                <label for="InputCategoryImage">Status</label>
                <div class="form-check form-check-inline">
                    <input class="form-check-input @error('status') is-invalid @enderror" type="radio" name="status" id="publish" checked value="true">
                    <label class="form-check-label" for="publish">Publish</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input @error('status') is-invalid @enderror" type="radio" name="status" id="unPublish" value="false">
                    <label class="form-check-label" for="unPublish">Unpublish</label>
                </div>


            </div>
            <button type="submit" class="btn btn-primary">Add Category</button>
            <a href="{{url('/category')}}" class="btn btn-light">Cancel</a>

        </form>
    </div>

    @endsection

resources/views/category/edit.blade.php
@extends('layouts.sidebar')
@section('content1')
    <div class="col-md-9">
        <form action="{{ route('category.update',$categories['id']) }}" method="post" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label for="InputCategoryName">Category Name</label>
                <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" id="InputCategoryName"
                       placeholder="Enter Category Name" value="{{$categories['name']}}">
                @error('name')
                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                @enderror
            </div>
            <div class="form-group">
                <label for="selectParentCategory">Parent Category</label>
                <select class="form-control" id="selectParentCategory" name="category_id">
                    <option value="0" @php if($categories['category_id']==0) { echo 'selected'; }@endphp>No Parent</option>
                    @foreach($category as $row)
                        <option value="{{ $row->id }}" @php if($categories['category_id']==$row->id) { echo 'selected'; }@endphp>{{ $row->name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <div class="col-lg-6">
                <label for="InputCategoryImage">Category Image</label>
                <input type="file" name="categoryimage" class="form-control @error('categoryimage') is-invalid @enderror" id="InputCategoryImage">
                @error('categoryimage')
                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                @enderror
                </div>
                <div class="col-lg-6">
                    <img src="{{ Storage::url($categories['categoryimage']) }}" width="50px" height="50px" />
                </div>
            </div>
            <input type="hidden" name="oldimage" value="{{$categories['categoryimage']}}"/>
            <div class="form-group">
                <label for="InputCategoryImage">Status</label>
                <div class="form-check form-check-inline">
                    <input class="form-check-input @error('status') is-invalid @enderror" type="radio" name="status" id="publish" @php if($categories['status']=='true') { echo 'checked'; }@endphp value="true">
                    <label class="form-check-label" for="publish">Publish</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input @error('status') is-invalid @enderror" type="radio" name="status" id="unPublish" @php if($categories['status']=='false') { echo 'checked'; }@endphp value="false">
                    <label class="form-check-label" for="unPublish">Unpublish</label>
                </div>
            </div>
            <button type="submit" class="btn btn-info">Update Category</button>
            <a href="{{url('/category')}}" class="btn btn-light">Cancel</a>

        </form>
    </div>

@endsection

resources/views/category/list.blade.php
@extends('layouts.sidebar')
@section('content1')
    <div class="col-md-9">
        <div class="row justify-content-center">
            <div class="col-md-11">
            </div>
            <div class="col-md-1 mb-2">
                <a href="{{url('/category/create')}}" class="btn btn-primary" >Add Category</a>

            </div>
        </div>

    <table class="table" id="category">
        <thead>
        <tr>
            <th scope="col">Category</th>
            <th scope="col">Parent Category</th>
            <th scope="col">Status</th>
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($category as $row)
        <tr>
            <th scope="row">{{$row->name}}</th>
            <td>{{isset($row->parentCategory->name) ? $row->parentCategory->name : "NA"}}</td>
            <td> @if($row->status=='true')
                    <span class="badge badge-success">Publish</span>
                @else
                    <span class="badge badge-danger">Un-publish</span>
                @endif
                </td>
            <td><a class="btn btn-sm btn-warning float-left" href="{{URL::to('category/'.$row->id.'/edit')}}">Edit</a>
                <form action="{{route('deleteestablishmentimage',$row->id)}}" method="post">
                 @csrf
                    <button type="submit" class="btn btn-sm btn-danger float-left ml-1" onclick="return confirm ('Are you sure to delete this category')">
                        Delete
                    </button>
                </form>
                </td>
        </tr>
            @endforeach
        </tbody>
    </table>
    </div>
    <script type="text/javascript">
        $(document).ready( function () {
            $('#category').DataTable();
        } );
    </script>


@endsection